server.port: 8080

forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
  variables:
    # FSM 的 api token
    "APITOKEN": "${FSM_APITOKEN}"

solon.app:
  name: 'fsm-app'
  group: 'app'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO