server.port: 8080

auto-table:
  enable: true
  banner: false
  model: update
  recordSql:
    enable: true
    recordType: file
    folderPath: ./sql

# 数据库配置
solon.dataSources:
  master!:
    class: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: jdbc:sqlite:data/data.db
    driverClassName: org.sqlite.JDBC

# xmybatis配置
mybatis.master:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mappers:       #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）；支持目录 ** 或 * 占位符
    - "com.layjava.auto.pause.mapper.CommonMapper"

forest:
  ## 日志总开关，打开/关闭Forest请求/响应日志（默认为 true）
  log-enabled: false
  ## 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  ## 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  ## 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
  variables:
    # FSM 的 api token
    "APITOKEN": "${FSM_APITOKEN}"
    "QBHOST": "${QB_HOST}"
    "QBUSERNAME": "${QB_USERNAME}"
    "QBPASSWORD": "${QB_PASSWORD}"

solon.app:
  name: 'fsm-app'
  group: 'app'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO